# Generated by Django 3.2.3 on 2021-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
