# Generated by Django 3.2.3 on 2021-08-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='badge_pics/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveBigIntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='price',
        ),
        migrations.AddField(
            model_name='customuser',
            name='features',
            field=models.ManyToManyField(related_name='users_features', to='users.Feature'),
        ),
    ]
