# Generated by Django 3.2.3 on 2021-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_image_feature_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='users_features', to='users.Feature'),
        ),
    ]
