# Generated by Django 3.2.1 on 2021-05-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('WebDevelopment', 'Web Development'), ('Covid19', 'Covid-19')], max_length=155),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
