# Generated by Django 3.2 on 2021-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Bookmarked',
        ),
    ]
