# Generated by Django 3.2.1 on 2021-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=155),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
