# Generated by Django 3.2.3 on 2021-08-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('WebDevelopment', 'Web Development'), ('Covid19', 'Covid-19'), ('Entertainment', 'Entertainment'), ('Music', 'Music'), ('News', 'News'), ('Movies', 'Movies'), ('Love', 'Love')], max_length=155, null=True),
        ),
    ]
