# Generated by Django 3.2.1 on 2021-05-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210506_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('WebDevelopment', 'Web Development'), ('Covid19', 'Covid-19')], max_length=155, null=True),
        ),
    ]
