# Generated by Django 3.2.1 on 2021-05-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('WebDevelopment', 'Web Development'), ('Covid19', 'Covid-19'), ('Entertainment', 'Entertainment'), ('Music', 'Music'), ('News', 'News'), ('sport', 'Sport')], max_length=155, null=True),
        ),
    ]
