# Generated by Django 3.2.3 on 2021-05-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210514_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='supporter',
        ),
        migrations.DeleteModel(
            name='Supporter',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
