# Generated by Django 3.2.1 on 2021-05-10 14:07

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210507_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
