# Generated by Django 3.2 on 2021-04-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dress',
        ),
    ]
