# Generated by Django 3.2 on 2021-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_dress'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gained_xp',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='article',
            name='needed_xp',
            field=models.IntegerField(default=10),
        ),
    ]
