# Generated by Django 3.2.3 on 2021-05-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
