# Generated by Django 3.2 on 2021-04-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210422_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='has_been_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='gained_xp',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='article',
            name='needed_xp',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
