# Generated by Django 3.2.3 on 2021-05-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likedCounter',
            field=models.BigIntegerField(default=0),
        ),
    ]
