# Generated by Django 3.2.1 on 2021-05-10 14:18

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_article_detail_page_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='detail_page_cropping',
            field=image_cropping.fields.ImageRatioField('image', '500x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='detail page cropping'),
        ),
    ]
