# Generated by Django 3.2.3 on 2021-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_article_likedcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likedCounter',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
