# Generated by Django 3.2.1 on 2021-05-10 14:37

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_article_detail_page_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cropping',
        ),
        migrations.AddField(
            model_name='article',
            name='default_cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='default cropping'),
        ),
    ]
