# Generated by Django 3.2.3 on 2021-05-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_article_likedcounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='liked',
            new_name='likes',
        ),
    ]
