# Generated by Django 3.2.1 on 2021-05-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_article_detail_page_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='detail_page_cropping',
        ),
    ]
