# Generated by Django 3.2.3 on 2021-05-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_liked_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
