# Generated by Django 3.2.3 on 2021-05-30 20:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_article_likes_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_detail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article_pics/'),
        ),
    ]
