# Generated by Django 3.2.3 on 2021-05-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_article_image_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_detail',
            new_name='image_thumbnail',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
