# Generated by Django 3.2.3 on 2021-05-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210530_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_thumbnail',
            new_name='image',
        ),
    ]
