# Generated by Django 3.2.3 on 2021-05-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_image_thumbnail_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image_thumbnail',
        ),
    ]
