# Generated by Django 3.2.3 on 2021-05-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_image_article_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes_counter',
        ),
    ]
