# Generated by Django 3.2.3 on 2021-06-03 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210603_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 15, 13, 53, 11233)),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 15, 13, 53, 11233)),
        ),
    ]
