# Generated by Django 3.2.3 on 2021-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
