# Generated by Django 3.2.3 on 2021-06-03 13:23

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_task_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
