# Generated by Django 3.2.3 on 2021-08-21 19:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
