# Generated by Django 3.2.3 on 2021-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'OPEN'), ('Closed', 'CLOSED')], default='Open', max_length=50),
        ),
    ]
