# Generated by Django 3.2.3 on 2021-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
