# Generated by Django 3.2.3 on 2021-05-23 10:54

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
