# Generated by Django 3.2.3 on 2021-05-23 11:19

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_ticket_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('content', martor.models.MartorField()),
            ],
        ),
    ]
