# Generated by Django 3.2.3 on 2021-05-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
