# Generated by Django 3.2.3 on 2021-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
