name: Test Django App

on: 
  push:
    branches: [ master ]


jobs:
  test_django_with_coverage:
    runs-on: ubuntu_latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python_version: 3.8
    - name: Install dependencies
      run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    - name: Install and run Coverage
      run: |
      pip install coverage
      coverage run manage.py test
      coverage report
    - name: Run Django Test
      run: python manage.py test
